name: 'mental_health_analytics'
version: '1.0.0'
config-version: 2

profile: 'mental_health_duckdb'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  mental_health_analytics:
    staging:
      +materialized: view
    
    marts:
      +materialized: table